### ISSUE TITLE
HttpSessionId is not included in any MVC log entry

### ISSUE THREAD

**Issue by douglasg14b** [serilog-web/classic-mvc#12]
The title pretty much describes the issue. I have log entries enriched with `HttpSessionId` which works for any other log entry, except for the automatic MVC action ones.

**Comment by tsimbalar** [comment]
Sorry for replying so late ... 

When you say `automatic MVC action ones` , what do yo refer to ?

**Comment by douglasg14b** [comment]
When using the enrichers included in this package.

**Comment by AroglDarthu** [comment]
Could it be that you are overwriting your enrichers? If you add the first set in `classicSettings.json` and then try to add additional enrichers via `.AddJsonFile("classicMvcSettings.json")` it will effectively overwrite your initial enricher array.

**Comment by douglasg14b** [comment]
I've deployed logging in 6 different systems now and observed this behavior in all, even with default implementations.

**Comment by tsimbalar** [comment]
This project is no longer being maintained and we are going to archive the SerilogWeb Repositories. 

see:
- https://github.com/serilog-web/classic/issues/82
